### ISSUE TITLE
Missing step?  No 'HelloWeb' etc. there by default

### ISSUE THREAD

**Issue by RickJWagner** [DonSchenck/DotNetOnLinux#1]
Thanks for providing hte excellent 'Getting Started' steps.  
I've just run through them on a clean RHEL7 machine, everything works great through completion of the CLI Hello World app.
The next steps deal with the samples for 'HelloWeb', 'HelloMVC', etc.  But the source for these is not present after following the steps above them.
Did I miss something?  Or do we need another git pull to get this source?

**Comment by DonSchenck** [comment]
Rick; Yeah ... the Getting Started is written from the perspective that one has downloaded or cloned this repo. In fact, I updated the README.md just moments ago to that end.

I'll going to add some instructions to the Getting Started as well, just to be safe. THANK YOU for this feedback.
