### ISSUE TITLE
dotnet restore throws "NewtonSoft.Json 8.0.3 is not compatible"

### ISSUE THREAD

**Issue by DonSchenck** [DonSchenck/DotNetOnLinux#12]
Errors in /home/vagrant/src/DotNetOnLinux/cli-samples-master/Speakr/project.json
    Package Newtonsoft.Json 8.0.3 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Newtonsoft.Json 8.0.3 supports:
      - net20 (.NETFramework,Version=v2.0)
      - net35 (.NETFramework,Version=v3.5)
      - net40 (.NETFramework,Version=v4.0)
      - net45 (.NETFramework,Version=v4.5)
      - portable-dnxcore50+net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=net45+wp80+win8+wpa81+dnxcore50)
      - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.
    Package Newtonsoft.Json 8.0.3 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Newtonsoft.Json 8.0.3 supports:
      - net20 (.NETFramework,Version=v2.0)
      - net35 (.NETFramework,Version=v3.5)
      - net40 (.NETFramework,Version=v4.0)
      - net45 (.NETFramework,Version=v4.5)
      - portable-dnxcore50+net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=net45+wp80+win8+wpa81+dnxcore50)
      - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.
    Package Newtonsoft.Json 8.0.3 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Newtonsoft.Json 8.0.3 supports:
      - net20 (.NETFramework,Version=v2.0)
      - net35 (.NETFramework,Version=v3.5)
      - net40 (.NETFramework,Version=v4.0)
      - net45 (.NETFramework,Version=v4.5)
      - portable-dnxcore50+net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=net45+wp80+win8+wpa81+dnxcore50)
      - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.

**Comment by dodyg** [comment]
I encountered this problem. How did you solve it?

**Comment by DonSchenck** [comment]
I simply ignored it, ran `dotnet run`, and everything is working great.

**Comment by dodyg** [comment]
I had to resort to this and the errors went away 
```
  "tools": {
    "dotnet-publish-iis": {
        "version": "1.0.0-*",
        "imports":["portable-net40+sl5+win8+wp8+wpa81"]
    },
    "dotnet-ef": {
        "version": "1.0.0-*",
        "imports":["portable-net40+sl5+win8+wp8+wpa81"]
    },
    "dotnet-watch": {
        "version": "1.0.0-*",
        "imports":["portable-net40+sl5+win8+wp8+wpa81"]
    },
    "dotnet-razor-tooling": {
        "version": "1.0.0-*",
        "imports":["portable-net40+sl5+win8+wp8+wpa81"]
    }
  },
```

**Comment by DonSchenck** [comment]
Thanks!

**Comment by cuoilennaocacban** [comment]
"Microsoft.Extensions.Configuration.UserSecrets": "1.0.0"
It's updated to version 1.0.0 now, and fix the problem too.
Right click on References > Manage Nuget Package... > Click Update tab > Update it
